// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queries_mocks

import (
	"context"

	"github.com/dzhordano/urlshortener/internal/core/application/usecases/queries"
	mock "github.com/stretchr/testify/mock"
)

// NewGetURLInfoQueryHandlerMock creates a new instance of GetURLInfoQueryHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetURLInfoQueryHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetURLInfoQueryHandlerMock {
	mock := &GetURLInfoQueryHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GetURLInfoQueryHandlerMock is an autogenerated mock type for the GetURLInfoQueryHandler type
type GetURLInfoQueryHandlerMock struct {
	mock.Mock
}

type GetURLInfoQueryHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *GetURLInfoQueryHandlerMock) EXPECT() *GetURLInfoQueryHandlerMock_Expecter {
	return &GetURLInfoQueryHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type GetURLInfoQueryHandlerMock
func (_mock *GetURLInfoQueryHandlerMock) Handle(context1 context.Context, getURLInfoQuery queries.GetURLInfoQuery) (queries.GetURLInfoResponse, error) {
	ret := _mock.Called(context1, getURLInfoQuery)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 queries.GetURLInfoResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, queries.GetURLInfoQuery) (queries.GetURLInfoResponse, error)); ok {
		return returnFunc(context1, getURLInfoQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, queries.GetURLInfoQuery) queries.GetURLInfoResponse); ok {
		r0 = returnFunc(context1, getURLInfoQuery)
	} else {
		r0 = ret.Get(0).(queries.GetURLInfoResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, queries.GetURLInfoQuery) error); ok {
		r1 = returnFunc(context1, getURLInfoQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GetURLInfoQueryHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type GetURLInfoQueryHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - context1 context.Context
//   - getURLInfoQuery queries.GetURLInfoQuery
func (_e *GetURLInfoQueryHandlerMock_Expecter) Handle(context1 interface{}, getURLInfoQuery interface{}) *GetURLInfoQueryHandlerMock_Handle_Call {
	return &GetURLInfoQueryHandlerMock_Handle_Call{Call: _e.mock.On("Handle", context1, getURLInfoQuery)}
}

func (_c *GetURLInfoQueryHandlerMock_Handle_Call) Run(run func(context1 context.Context, getURLInfoQuery queries.GetURLInfoQuery)) *GetURLInfoQueryHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queries.GetURLInfoQuery
		if args[1] != nil {
			arg1 = args[1].(queries.GetURLInfoQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GetURLInfoQueryHandlerMock_Handle_Call) Return(getURLInfoResponse queries.GetURLInfoResponse, err error) *GetURLInfoQueryHandlerMock_Handle_Call {
	_c.Call.Return(getURLInfoResponse, err)
	return _c
}

func (_c *GetURLInfoQueryHandlerMock_Handle_Call) RunAndReturn(run func(context1 context.Context, getURLInfoQuery queries.GetURLInfoQuery) (queries.GetURLInfoResponse, error)) *GetURLInfoQueryHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}
