// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queries_mocks

import (
	"context"

	"github.com/dzhordano/urlshortener/internal/core/application/usecases/queries"
	mock "github.com/stretchr/testify/mock"
)

// NewRedirectQueryHandlerMock creates a new instance of RedirectQueryHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedirectQueryHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedirectQueryHandlerMock {
	mock := &RedirectQueryHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RedirectQueryHandlerMock is an autogenerated mock type for the RedirectQueryHandler type
type RedirectQueryHandlerMock struct {
	mock.Mock
}

type RedirectQueryHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RedirectQueryHandlerMock) EXPECT() *RedirectQueryHandlerMock_Expecter {
	return &RedirectQueryHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type RedirectQueryHandlerMock
func (_mock *RedirectQueryHandlerMock) Handle(context1 context.Context, redirectQuery queries.RedirectQuery) (queries.RedirectResponse, error) {
	ret := _mock.Called(context1, redirectQuery)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 queries.RedirectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, queries.RedirectQuery) (queries.RedirectResponse, error)); ok {
		return returnFunc(context1, redirectQuery)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, queries.RedirectQuery) queries.RedirectResponse); ok {
		r0 = returnFunc(context1, redirectQuery)
	} else {
		r0 = ret.Get(0).(queries.RedirectResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, queries.RedirectQuery) error); ok {
		r1 = returnFunc(context1, redirectQuery)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RedirectQueryHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type RedirectQueryHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - context1 context.Context
//   - redirectQuery queries.RedirectQuery
func (_e *RedirectQueryHandlerMock_Expecter) Handle(context1 interface{}, redirectQuery interface{}) *RedirectQueryHandlerMock_Handle_Call {
	return &RedirectQueryHandlerMock_Handle_Call{Call: _e.mock.On("Handle", context1, redirectQuery)}
}

func (_c *RedirectQueryHandlerMock_Handle_Call) Run(run func(context1 context.Context, redirectQuery queries.RedirectQuery)) *RedirectQueryHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 queries.RedirectQuery
		if args[1] != nil {
			arg1 = args[1].(queries.RedirectQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RedirectQueryHandlerMock_Handle_Call) Return(redirectResponse queries.RedirectResponse, err error) *RedirectQueryHandlerMock_Handle_Call {
	_c.Call.Return(redirectResponse, err)
	return _c
}

func (_c *RedirectQueryHandlerMock_Handle_Call) RunAndReturn(run func(context1 context.Context, redirectQuery queries.RedirectQuery) (queries.RedirectResponse, error)) *RedirectQueryHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}
