all: false
dir: ./mocks
recursive: true
filename: "{{.InterfaceName}}.go"
structname: "{{.InterfaceName}}Mock"
pkgname: "{{.SrcPackageName}}_mocks"
packages:
  github.com/dzhordano/urlshortener/internal/core/ports:
    config:
      all: true
      dir: ./mocks/core/ports_mocks
  github.com/dzhordano/urlshortener/internal/core/application/usecases/commands:
    config:
      all: true
      dir: ./mocks/core/application_mocks/commands
  github.com/dzhordano/urlshortener/internal/core/application/usecases/queries:
    config:
      all: true
      dir: ./mocks/core/application_mocks/queries