// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports_mocks

import (
	"context"

	"github.com/dzhordano/urlshortener/internal/core/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewURLRepositoryMock creates a new instance of URLRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLRepositoryMock {
	mock := &URLRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// URLRepositoryMock is an autogenerated mock type for the URLRepository type
type URLRepositoryMock struct {
	mock.Mock
}

type URLRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *URLRepositoryMock) EXPECT() *URLRepositoryMock_Expecter {
	return &URLRepositoryMock_Expecter{mock: &_m.Mock}
}

// GetByOriginalURL provides a mock function for the type URLRepositoryMock
func (_mock *URLRepositoryMock) GetByOriginalURL(ctx context.Context, originalURL string) (*model.ShortenedURL, error) {
	ret := _mock.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByOriginalURL")
	}

	var r0 *model.ShortenedURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortenedURL, error)); ok {
		return returnFunc(ctx, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortenedURL); ok {
		r0 = returnFunc(ctx, originalURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortenedURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// URLRepositoryMock_GetByOriginalURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOriginalURL'
type URLRepositoryMock_GetByOriginalURL_Call struct {
	*mock.Call
}

// GetByOriginalURL is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *URLRepositoryMock_Expecter) GetByOriginalURL(ctx interface{}, originalURL interface{}) *URLRepositoryMock_GetByOriginalURL_Call {
	return &URLRepositoryMock_GetByOriginalURL_Call{Call: _e.mock.On("GetByOriginalURL", ctx, originalURL)}
}

func (_c *URLRepositoryMock_GetByOriginalURL_Call) Run(run func(ctx context.Context, originalURL string)) *URLRepositoryMock_GetByOriginalURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *URLRepositoryMock_GetByOriginalURL_Call) Return(shortenedURL *model.ShortenedURL, err error) *URLRepositoryMock_GetByOriginalURL_Call {
	_c.Call.Return(shortenedURL, err)
	return _c
}

func (_c *URLRepositoryMock_GetByOriginalURL_Call) RunAndReturn(run func(ctx context.Context, originalURL string) (*model.ShortenedURL, error)) *URLRepositoryMock_GetByOriginalURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetByShortenedURL provides a mock function for the type URLRepositoryMock
func (_mock *URLRepositoryMock) GetByShortenedURL(ctx context.Context, shortenedURL string) (*model.ShortenedURL, error) {
	ret := _mock.Called(ctx, shortenedURL)

	if len(ret) == 0 {
		panic("no return value specified for GetByShortenedURL")
	}

	var r0 *model.ShortenedURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortenedURL, error)); ok {
		return returnFunc(ctx, shortenedURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortenedURL); ok {
		r0 = returnFunc(ctx, shortenedURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortenedURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortenedURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// URLRepositoryMock_GetByShortenedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByShortenedURL'
type URLRepositoryMock_GetByShortenedURL_Call struct {
	*mock.Call
}

// GetByShortenedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - shortenedURL string
func (_e *URLRepositoryMock_Expecter) GetByShortenedURL(ctx interface{}, shortenedURL interface{}) *URLRepositoryMock_GetByShortenedURL_Call {
	return &URLRepositoryMock_GetByShortenedURL_Call{Call: _e.mock.On("GetByShortenedURL", ctx, shortenedURL)}
}

func (_c *URLRepositoryMock_GetByShortenedURL_Call) Run(run func(ctx context.Context, shortenedURL string)) *URLRepositoryMock_GetByShortenedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *URLRepositoryMock_GetByShortenedURL_Call) Return(shortenedURL1 *model.ShortenedURL, err error) *URLRepositoryMock_GetByShortenedURL_Call {
	_c.Call.Return(shortenedURL1, err)
	return _c
}

func (_c *URLRepositoryMock_GetByShortenedURL_Call) RunAndReturn(run func(ctx context.Context, shortenedURL string) (*model.ShortenedURL, error)) *URLRepositoryMock_GetByShortenedURL_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type URLRepositoryMock
func (_mock *URLRepositoryMock) Save(ctx context.Context, url *model.ShortenedURL) error {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ShortenedURL) error); ok {
		r0 = returnFunc(ctx, url)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// URLRepositoryMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type URLRepositoryMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - url *model.ShortenedURL
func (_e *URLRepositoryMock_Expecter) Save(ctx interface{}, url interface{}) *URLRepositoryMock_Save_Call {
	return &URLRepositoryMock_Save_Call{Call: _e.mock.On("Save", ctx, url)}
}

func (_c *URLRepositoryMock_Save_Call) Run(run func(ctx context.Context, url *model.ShortenedURL)) *URLRepositoryMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ShortenedURL
		if args[1] != nil {
			arg1 = args[1].(*model.ShortenedURL)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *URLRepositoryMock_Save_Call) Return(err error) *URLRepositoryMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *URLRepositoryMock_Save_Call) RunAndReturn(run func(ctx context.Context, url *model.ShortenedURL) error) *URLRepositoryMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
