{
 "title": "Some Dashboards",
 "tags": [
  "app",
  "urlshortener"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Usage (Megabytes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes[$__rate_interval])*1e-6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL Shortener App CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API response times (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(echo_http_request_duration_seconds_bucket[$__rate_interval])) by (le, handler))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL Redirects Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total{handler=\"/api/v1/:token\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URL Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total{handler=\"/api/v1/shorten\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Errors (4xx/5xx) Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total{status=~\"4..|5..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Traces",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    { "service": "urlshortener-service" }
   ]
  },
  {
   "title": "URL Shortener App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"urlshortener_app\"} |= `` | label_format level=detected_level"
    }
   ]
  }
 ]
}