// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commands_mocks

import (
	"context"

	"github.com/dzhordano/urlshortener/internal/core/application/usecases/commands"
	mock "github.com/stretchr/testify/mock"
)

// NewShortenURLCommandHandlerMock creates a new instance of ShortenURLCommandHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShortenURLCommandHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShortenURLCommandHandlerMock {
	mock := &ShortenURLCommandHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShortenURLCommandHandlerMock is an autogenerated mock type for the ShortenURLCommandHandler type
type ShortenURLCommandHandlerMock struct {
	mock.Mock
}

type ShortenURLCommandHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ShortenURLCommandHandlerMock) EXPECT() *ShortenURLCommandHandlerMock_Expecter {
	return &ShortenURLCommandHandlerMock_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type ShortenURLCommandHandlerMock
func (_mock *ShortenURLCommandHandlerMock) Handle(context1 context.Context, shortenURLCommand commands.ShortenURLCommand) (string, error) {
	ret := _mock.Called(context1, shortenURLCommand)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, commands.ShortenURLCommand) (string, error)); ok {
		return returnFunc(context1, shortenURLCommand)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, commands.ShortenURLCommand) string); ok {
		r0 = returnFunc(context1, shortenURLCommand)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, commands.ShortenURLCommand) error); ok {
		r1 = returnFunc(context1, shortenURLCommand)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShortenURLCommandHandlerMock_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type ShortenURLCommandHandlerMock_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - context1 context.Context
//   - shortenURLCommand commands.ShortenURLCommand
func (_e *ShortenURLCommandHandlerMock_Expecter) Handle(context1 interface{}, shortenURLCommand interface{}) *ShortenURLCommandHandlerMock_Handle_Call {
	return &ShortenURLCommandHandlerMock_Handle_Call{Call: _e.mock.On("Handle", context1, shortenURLCommand)}
}

func (_c *ShortenURLCommandHandlerMock_Handle_Call) Run(run func(context1 context.Context, shortenURLCommand commands.ShortenURLCommand)) *ShortenURLCommandHandlerMock_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 commands.ShortenURLCommand
		if args[1] != nil {
			arg1 = args[1].(commands.ShortenURLCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ShortenURLCommandHandlerMock_Handle_Call) Return(s string, err error) *ShortenURLCommandHandlerMock_Handle_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *ShortenURLCommandHandlerMock_Handle_Call) RunAndReturn(run func(context1 context.Context, shortenURLCommand commands.ShortenURLCommand) (string, error)) *ShortenURLCommandHandlerMock_Handle_Call {
	_c.Call.Return(run)
	return _c
}
